---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: ublue-custom-os
# description will be included in the image's metadata
description: Buzzle's ublue image.

# the base image to build on top of (FROM) and the version tag to use
base-image: quay.io/fedora/fedora-bootc
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: script
    scripts:
      - 00-reposetup.sh

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      - akmod-nvidia
      - micro
      - flatpak
      - greetd
      - mozilla-fira-mono-fonts
      - nerd-fonts
      - podman-bootc
      - podman-compose
      - podman-machine
      - podman-tui
      - podmansh
      - python3-pip
      - tuigreet
      - vulkan
      - hyprland
      - foot
      - wofi
      - waybar
      - vifm
      - git
      - just
      - wpctl
      - brightnessctl
      - playerctl
      - firewalld
      - network-manager-applet
      - hyprpaper
      - hyprlock
      - hypridle
      - blueman
      - polkit-kde
      - distrobox
    # remove: {}

  - type: script
    scripts:
      - 50-customizations.sh
      - 51-brew.sh

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      install:
        - org.mozilla.firefox
    user: {} # Also add Flathub user repo, but no user packages

  - type: initramfs

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

